-- Creating the MSEQP table
CREATE TABLE MSEQP (
    EQPCOD VARCHAR(30)  NULL ,
    EQPDSC VARCHAR(100)  NULL ,
    EQPMAR VARCHAR(100)  NULL ,
    EQPSU1 VARCHAR(100)  NULL ,
    EQPSU2 VARCHAR(100)  NULL ,
    EQPSU3 VARCHAR(100)  NULL ,
    EQPNSR VARCHAR(1)  NULL ,
    EQPSU4 VARCHAR(100)  NULL ,
    EQPSU5 VARCHAR(100)  NULL ,
    EQPSU6 VARCHAR(100)  NULL ,
    EQPSU7 VARCHAR(100)  NULL ,
    EQPSU8 VARCHAR(100)  NULL ,
    EQPSU9 VARCHAR(100)  NULL ,
	EQPACL VARCHAR(2000) NULL ,
	EQPVND VARCHAR(50)  NULL ,
	EQPSYNCR VARCHAR(1) NULL
	EQPTIPO VARCHAR(1) NULL,
	EQPTERM BIGINT NULL );
CREATE UNIQUE INDEX WDIDX_MSEQP_EQPK01 ON MSEQP (EQPCOD,EQPTERM);
CREATE INDEX WDIDX_MSEQP_EQPVND ON MSEQP (EQPVND);
CREATE INDEX WDIDX_MSEQP_EQPSYN ON MSEQP (EQPSYNCR);