-- Creating the MSRCI table
CREATE TABLE MSRCI ( 
    RCIEXR VARCHAR( 60 ),
    RCITPD VARCHAR( 20 ),
    RCISER VARCHAR( 20 ),
    RCINDC BIGINT,
    RCILIN BIGINT,
    RCILIL BIGINT,
    RCITXI DECIMAL( 5, 2 ),
    RCIVLB DECIMAL( 12, 3 ),
    RCIVLI DECIMAL( 12, 3 ),
    RCIVLA DECIMAL( 12, 6 ),
    RCIVLR DECIMAL( 12, 6 ),
    RCITIP VARCHAR( 100 ),
    RCIPRG VARCHAR( 100 ),
    RCIPLI VARCHAR( 1000 ),
    RCICMI VARCHAR( 100 ),
    RCIACL VARCHAR( 4000 ),
	RCIVND VARCHAR(50)  NULL,
    RCISYNCR VARCHAR(1) NULL,
	RCITIPO VARCHAR(1) NULL,
	RCITERM BIGINT NULL);
CREATE UNIQUE INDEX WDIDX_MSRCI_RCIK01 ON MSRCI (RCIEXR,RCITPD,RCISER,RCINDC,RCILIN,RCILIL);
CREATE INDEX WDIDX_MSRCI_RCIVND ON MSRCI (RCIVND);
CREATE INDEX WDIDX_MSRCI_RCISYNCR ON MSRCI (RCISYNCR);
GO

-- Creating the MSCBI table
CREATE TABLE MSCBI ( 
    CBIEXR VARCHAR( 60 ),
    CBITPD VARCHAR( 20 ),
    CBISER VARCHAR( 20 ),
    CBINDC BIGINT,
    CBILIN BIGINT,
    CBILIL BIGINT,
    CBITXI DECIMAL( 5, 2 ),
    CBIVLB DECIMAL( 12, 3 ),
    CBIVLI DECIMAL( 12, 3 ),
    CBIVLA DECIMAL( 12, 6 ),
    CBIVLR DECIMAL( 12, 6 ),
    CBITIP VARCHAR( 100 ),
    CBIPRG VARCHAR( 100 ),
    CBIPLI VARCHAR( 1000 ),
    CBICMI VARCHAR( 100 ),
    CBIACL VARCHAR( 4000 ),
    CBIVND VARCHAR(50)  NULL,
    CBISYNCR VARCHAR(1) NULL,
	CBITIPO VARCHAR(1) NULL,
	CBITERM BIGINT NULL);
CREATE UNIQUE INDEX WDIDX_MSCBI_CBIK01 ON MSCBI (CBIEXR,CBITPD,CBISER,CBINDC,CBILIN,CBILIL);
CREATE INDEX WDIDX_MSCBI_CBIVND ON MSCBI (CBIVND);
CREATE INDEX WDIDX_MSCBI_CBISYNCR ON MSCBI (CBISYNCR);
GO