CREATE DATABASE SYSLOG_DATA;
GO
IF (select FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))=1
begin
	EXEC SYSLOG_DATA.dbo.sp_fulltext_database @action = 'enable';
end
GO
ALTER DATABASE SYSLOG_DATA SET ANSI_NULL_DEFAULT OFF;
ALTER DATABASE SYSLOG_DATA SET ANSI_NULLS OFF;
ALTER DATABASE SYSLOG_DATA SET ANSI_PADDING OFF;
ALTER DATABASE SYSLOG_DATA SET ANSI_WARNINGS OFF;
ALTER DATABASE SYSLOG_DATA SET ARITHABORT OFF;
ALTER DATABASE SYSLOG_DATA SET AUTO_CLOSE OFF;
ALTER DATABASE SYSLOG_DATA SET AUTO_SHRINK OFF;
ALTER DATABASE SYSLOG_DATA SET AUTO_UPDATE_STATISTICS ON;
ALTER DATABASE SYSLOG_DATA SET CURSOR_CLOSE_ON_COMMIT OFF;
ALTER DATABASE SYSLOG_DATA SET CURSOR_DEFAULT  GLOBAL;
ALTER DATABASE SYSLOG_DATA SET CONCAT_NULL_YIELDS_NULL OFF;
ALTER DATABASE SYSLOG_DATA SET NUMERIC_ROUNDABORT OFF;
ALTER DATABASE SYSLOG_DATA SET QUOTED_IDENTIFIER OFF;
ALTER DATABASE SYSLOG_DATA SET RECURSIVE_TRIGGERS OFF;
ALTER DATABASE SYSLOG_DATA SET DISABLE_BROKER;
ALTER DATABASE SYSLOG_DATA SET AUTO_UPDATE_STATISTICS_ASYNC OFF;
ALTER DATABASE SYSLOG_DATA SET DATE_CORRELATION_OPTIMIZATION OFF;
ALTER DATABASE SYSLOG_DATA SET TRUSTWORTHY OFF;
ALTER DATABASE SYSLOG_DATA SET ALLOW_SNAPSHOT_ISOLATION OFF;
ALTER DATABASE SYSLOG_DATA SET PARAMETERIZATION SIMPLE;
ALTER DATABASE SYSLOG_DATA SET READ_COMMITTED_SNAPSHOT OFF;
ALTER DATABASE SYSLOG_DATA SET HONOR_BROKER_PRIORITY OFF;
ALTER DATABASE SYSLOG_DATA SET RECOVERY SIMPLE;
ALTER DATABASE SYSLOG_DATA SET MULTI_USER;
ALTER DATABASE SYSLOG_DATA SET PAGE_VERIFY CHECKSUM ;
ALTER DATABASE SYSLOG_DATA SET DB_CHAINING OFF;
EXEC sys.sp_db_vardecimal_storage_format N'SYSLOG_DATA', N'ON';
GO
ALTER DATABASE SYSLOG_DATA SET  READ_WRITE;
GO
