CREATE TRIGGER TR_MSSAGR_CHECK_DUPLICATE ON MSAGR INSTEAD OF INSERT
AS 
BEGIN
	SET NOCOUNT ON;

	DECLARE @Stamp VARCHAR(40)
	DECLARE @LogCount INT

	SELECT @Stamp = AGRSTP FROM INSERTED
	SELECT @LogCount = Count(*) FROM MSAGR(nolock) WHERE AGRSTP = @Stamp
	IF @LogCount > 0
		DELETE FROM MSAGR WHERE AGRSTP = @Stamp

	INSERT INTO MSAGR SELECT * FROM INSERTED
END
GO