-- Re-create the main index
DROP INDEX WDIDX_MSBCC_BCCK01 ON MSBCC
CREATE UNIQUE INDEX WDIDX_MSBCC_BCCK01 ON MSBCC (BCCEXR, BCCSER,BCCNDC,BCCTERM);

DROP INDEX WDIDX_MSBCL_BCLK01 ON MSBCL
CREATE UNIQUE INDEX WDIDX_MSBCL_BCLK01 ON MSBCL (BCLEXR,BCLSER,BCLNDC,BCLLIN,BCLTERM);

DROP INDEX WDIDX_MSCBC_CBCK01 ON MSCBC
CREATE UNIQUE INDEX WDIDX_MSCBC_CBCK01 ON MSCBC (CBCEXR,CBCTPD,CBCSER,CBCNDC,CBCTERM);

DROP INDEX WDIDX_MSCBD_CBDK01 ON MSCBD 
CREATE UNIQUE INDEX WDIDX_MSCBD_CBDK01 ON MSCBD (CBDEXR,CBDTPD,CBDSER,CBDNDC,CBDLIN,CBDTERM);

DROP INDEX WDIDX_MSCBP_CBPK01 ON MSCBP 
CREATE UNIQUE INDEX WDIDX_MSCBP_CBPK01 ON MSCBP (CBPEXR,CBPTPD,CBPSER,CBPNDC,CBPLIN,CBPTERM);

DROP INDEX WDIDX_MSCLI_CLIK01 ON MSCLI 
CREATE UNIQUE INDEX WDIDX_MSCLI_CLIK01 ON MSCLI (CLICOD,CLITERM);

DROP INDEX WDIDX_MSCNT_CNTK01 ON MSCNT 
CREATE UNIQUE INDEX WDIDX_MSCNT_CNTK01 ON MSCNT (CNTCLI,CNTLCE,CNTCID,CNTTERM);

DROP INDEX WDIDX_MSCON_CONK01 ON MSCON 
CREATE UNIQUE INDEX WDIDX_MSCON_CONK01 ON MSCON (CONCOD,CONTERM);

DROP INDEX WDIDX_MSCRT_CRTK01 ON MSCRT 
CREATE UNIQUE INDEX WDIDX_MSCRT_CRTK01 ON MSCRT (CRTROT,CRTSBT,CRTCLI,CRTTERM);

DROP INDEX WDIDX_MSDCC_DCCK01 ON MSDCC 
CREATE UNIQUE INDEX WDIDX_MSDCC_DCCK01 ON MSDCC (DCCEXR,DCCTPD,DCCSER,DCCNDC,DCCTERM);

DROP INDEX WDIDX_MSDCG_DCGK01 ON MSDCG 
CREATE UNIQUE INDEX WDIDX_MSDCG_DCGK01 ON MSDCG (DCGEXR,DCGTPD,DCGSER,DCGNDC,DCGLIN,DCGLIG,DCGTERM);

DROP INDEX WDIDX_MSDCL_DCLK01 ON MSDCL 
CREATE UNIQUE INDEX WDIDX_MSDCL_DCLK01 ON MSDCL (DCLEXR,DCLTPD,DCLSER,DCLNDC,DCLLIN,DCLTERM);

DROP INDEX WDIDX_MSDCP_DCPK01 ON MSDCP 
CREATE UNIQUE INDEX WDIDX_MSDCP_DCPK01 ON MSDCP (DCPEXR,DCPTPD,DCPSER,DCPNDC,DCPLIN,DCPTERM);

DROP INDEX WDIDX_MSDCT_DCTK01 ON MSDCT 
CREATE UNIQUE INDEX WDIDX_MSDCT_DCTK01 ON MSDCT (DCTEXR,DCTTPD,DCTSER,DCTNDC,DCTLIN,DCTLIL,DCTTERM);

DROP INDEX WDIDX_MSDEC_DECK01 ON MSDEC 
CREATE UNIQUE INDEX WDIDX_MSDEC_DECK01 ON MSDEC (DECEXR,DECTPD,DECSER,DECNDC,DECTERM);

DROP INDEX WDIDX_MSDED_DEDK01 ON MSDED 
CREATE UNIQUE INDEX WDIDX_MSDED_DEDK01 ON MSDED (DEDEXR,DEDTPD,DEDSER,DEDNDC,DEDLIN,DEDTERM);

DROP INDEX WDIDX_MSDET_DETK01 ON MSDET 
CREATE UNIQUE INDEX WDIDX_MSDET_DETK01 ON MSDET (DETEXR,DETTPD,DETSER,DETNDC,DETLIN,DETLIL,DETTERM);

DROP INDEX WDIDX_MSDIA_DIAK01 ON MSDIA 
CREATE UNIQUE INDEX WDIDX_MSDIA_DIAK01 ON MSDIA (DIADTI,DIAHRI,DIATERM);

DROP INDEX WDIDX_MSDPS_DPSK01 ON MSDPS 
CREATE UNIQUE INDEX WDIDX_MSDPS_DPSK01 ON MSDPS (DPSEXR,DPSSER,DPSNUM,DPSTERM);

DROP INDEX WDIDX_MSEQC_EQCK01 ON MSEQC 
CREATE UNIQUE INDEX WDIDX_MSEQC_EQCK01 ON MSEQC (EQCCOD,EQCTERM);

DROP INDEX WDIDX_MSEQR_EQRK01 ON MSEQR 
CREATE UNIQUE INDEX WDIDX_MSEQR_EQRK01 ON MSEQR (EQRSER,EQRNDC,EQRTERM);

DROP INDEX WDIDX_MSLCE_LCEK01 ON MSLCE 
CREATE UNIQUE INDEX WDIDX_MSLCE_LCEK01 ON MSLCE (LCECOD,LCELCE,LCETERM);

DROP INDEX WDIDX_MSLGG_LGGK01 ON MSLGG 
CREATE UNIQUE INDEX WDIDX_MSLGG_LGGK01 ON MSLGG (LGGDAT,LGGHOR,LGGTERM);

DROP INDEX WDIDX_MSMSG_MSGK01 ON MSMSG 
CREATE UNIQUE INDEX WDIDX_MSMSG_MSGK01 ON MSMSG (MSGDAT,MSGHOR,MSGTERM);

DROP INDEX WDIDX_MSOPL_OPLK01 ON MSOPL 
CREATE UNIQUE INDEX WDIDX_MSOPL_OPLK01 ON MSOPL (OPLEXR,OPLSER,OPLNDC,OPLLIN,OPLTERM);

DROP INDEX WDIDX_MSOPO_OPOK01 ON MSOPO 
CREATE UNIQUE INDEX WDIDX_MSOPO_OPOK01 ON MSOPO (OPOEXR,OPOSER,OPONDC,OPOTERM);

DROP INDEX WDIDX_MSRCC_RCCK01 ON MSRCC 
CREATE UNIQUE INDEX WDIDX_MSRCC_RCCK01 ON MSRCC (RCCEXR,RCCTPD,RCCSER,RCCNDC,RCCTERM);

DROP INDEX WDIDX_MSRCL_RCLK01 ON MSRCL 
CREATE UNIQUE INDEX WDIDX_MSRCL_RCLK01 ON MSRCL (RCLEXR,RCLTPD,RCLSER,RCLNDC,RCLLIN,RCLTERM);

DROP INDEX WDIDX_MSRCP_RCPK01 ON MSRCP 
CREATE UNIQUE INDEX WDIDX_MSRCP_RCPK01 ON MSRCP (RCPEXR,RCPTPD,RCPSER,RCPNDC,RCPLIN,RCPTERM);

DROP INDEX WDIDX_MSRGC_RGCK01 ON MSRGC 
CREATE UNIQUE INDEX WDIDX_MSRGC_RGCK01 ON MSRGC (RGCEXR,RGCSER,RGCNDC,RGCTERM);

DROP INDEX WDIDX_MSRGL_RGLK01 ON MSRGL 
CREATE UNIQUE INDEX WDIDX_MSRGL_RGLK01 ON MSRGL (RGLEXR,RGLSER,RGLNDC,RGLLIN,RGLTERM);

DROP INDEX WDIDX_MSRTV_RTVK01 ON MSRTV 
CREATE UNIQUE INDEX WDIDX_MSRTV_RTVK01 ON MSRTV (RTVEXR,RTVSER,RTVNDC,RTVTERM);

DROP INDEX WDIDX_MSSBD_SBDK01 ON MSSBD 
CREATE UNIQUE INDEX WDIDX_MSSBD_SBDK01 ON MSSBD (SBDSTP,SBDTERM);

DROP INDEX WDIDX_MSSCL_SCLK01 ON MSSCL 
CREATE UNIQUE INDEX WDIDX_MSSCL_SCLK01 ON MSSCL (SCLEXR,SCLSER,SCLNDC,SCLLIN,SCLTERM);

DROP INDEX WDIDX_MSSEQ_SEQK01 ON MSSEQ 
CREATE UNIQUE INDEX WDIDX_MSSEQ_SEQK01 ON MSSEQ (SEQEXR,SEQSER,SEQNDC,SEQLIN,SEQTERM);

DROP INDEX WDIDX_MSSIT_SITK01 ON MSSIT
CREATE UNIQUE INDEX WDIDX_MSSIT_SITK01 ON MSSIT (SITEXR,SITSER,SITNDC,SITLIN,SITTERM);

DROP INDEX WDIDX_MSSLN_SLNK01 ON MSSLN 
CREATE UNIQUE INDEX WDIDX_MSSLN_SLNK01 ON MSSLN (SLNEXR,SLNSER,SLNNDC,SLNLEQ,SLNLIN,SLNLIL,SLNTERM);

DROP INDEX WDIDX_MSSMT_SMTK01 ON MSSMT 
CREATE UNIQUE INDEX WDIDX_MSSMT_SMTK01 ON MSSMT (SMTEXR,SMTSER,SMTNDC,SMTLEQ,SMTLIN,SMTTERM);

DROP INDEX WDIDX_MSSRV_SRVK01 ON MSSRV 
CREATE UNIQUE INDEX WDIDX_MSSRV_SRVK01 ON MSSRV (SRVEXR,SRVSER,SRVNDC,SRVTERM);

DROP INDEX WDIDX_MSTU1_TU1K01 ON MSTU1 
CREATE UNIQUE INDEX WDIDX_MSTU1_TU1K01 ON MSTU1 (TU1KU1,TU1KU2,TU1KU3,TU1KU4,TU1TERM);

DROP INDEX WDIDX_MSTU2_TU2K01 ON MSTU2 
CREATE UNIQUE INDEX WDIDX_MSTU2_TU2K01 ON MSTU2 (TU2KU1,TU2KU2,TU2KU3,TU2KU4,TU2TERM);

DROP INDEX WDIDX_MSTU3_TU3K01 ON MSTU3 
CREATE UNIQUE INDEX WDIDX_MSTU3_TU3K01 ON MSTU3 (TU3KU1,TU3KU2,TU3KU3,TU3KU4,TU3KU5,TU3KU6,TU3KU7,TU3KU8,TU3TERM);

DROP INDEX WDIDX_MSTU4_TU4K01 ON MSTU4 
CREATE UNIQUE INDEX WDIDX_MSTU4_TU4K01 ON MSTU4 (TU4KU1,TU4KU2,TU4KU3,TU4KU4,TU4KU5,TU4KU6,TU4KU7,TU4KU8,TU4TERM);
