--********************* TR_MSSBCC_CHECK_DUPLICATE ************************************
DROP TRIGGER TR_MSSBCC_CHECK_DUPLICATE 
GO

CREATE TRIGGER TR_MSSBCC_CHECK_DUPLICATE ON MSBCC INSTEAD OF INSERT
AS 
BEGIN
	SET NOCOUNT ON;

	DECLARE @BCCEXR VARCHAR(30)
	DECLARE @BCCSER VARCHAR(10)
	DECLARE @BCCNDC INT
	DECLARE @Terminal INT
	
	DECLARE @DiaCount INT

	SELECT @BCCEXR = BCCEXR, @BCCSER = BCCSER, @BCCNDC = BCCNDC, @Terminal = BCCTERM FROM INSERTED
	SELECT @DiaCount = Count(*) FROM MSBCC(nolock) WHERE BCCEXR = @BCCEXR AND BCCSER = @BCCSER AND BCCNDC = @BCCNDC AND BCCTERM = @Terminal
	IF @DiaCount > 0
		DELETE FROM MSBCC WHERE BCCEXR = @BCCEXR AND BCCSER = @BCCSER AND BCCNDC = @BCCNDC AND BCCTERM = @Terminal

	INSERT INTO MSBCC SELECT * FROM INSERTED
END
GO
--********************* // TR_MSSBCL_CHECK_DUPLICATE ************************************

--********************* TR_MSSBCL_CHECK_DUPLICATE ************************************
DROP TRIGGER TR_MSSBCL_CHECK_DUPLICATE 
GO

CREATE TRIGGER TR_MSSBCL_CHECK_DUPLICATE ON MSBCL INSTEAD OF INSERT
AS 
BEGIN
	SET NOCOUNT ON;

	DECLARE @BCLEXR VARCHAR(30)
	DECLARE @BCLSER VARCHAR(10)
	DECLARE @BCLNDC INT
	DECLARE @BCLLIN INT
	DECLARE @Terminal INT
	
	DECLARE @DiaCount INT

	SELECT @BCLEXR = BCLEXR, @BCLSER = BCLSER, @BCLNDC = BCLNDC, @BCLLIN = BCLLIN, @Terminal = BCLTERM FROM INSERTED
	SELECT @DiaCount = Count(*) FROM MSBCL(nolock) WHERE BCLEXR = @BCLEXR AND BCLSER = @BCLSER AND BCLNDC = @BCLNDC AND BCLLIN = @BCLLIN AND BCLTERM = @Terminal
	IF @DiaCount > 0
		DELETE FROM MSBCL WHERE BCLEXR = @BCLEXR AND BCLSER = @BCLSER AND BCLNDC = @BCLNDC AND BCLLIN = @BCLLIN AND BCLTERM = @Terminal

	INSERT INTO MSBCL SELECT * FROM INSERTED
END
GO
--********************* // TR_MSSBCL_CHECK_DUPLICATE ************************************