CREATE TRIGGER TR_MSSLOG_CHECK_DUPLICATE ON MSLOG INSTEAD OF INSERT
AS 
BEGIN
	SET NOCOUNT ON;

	DECLARE @Stamp VARCHAR(30)
	DECLARE @LogCount INT

	SELECT @Stamp = LOGSTP FROM INSERTED
	SELECT @LogCount = Count(*) FROM MSLOG(nolock) WHERE LOGSTP = @Stamp
	IF @LogCount > 0
		DELETE FROM MSLOG WHERE LOGSTP = @Stamp

	INSERT INTO MSLOG SELECT * FROM INSERTED
END
GO