-- Creating the MSLOG table
CREATE table MSLOG (
	LOGSTP VARCHAR(60),
	LOGGRP VARCHAR(40),
	LOGDAT VARCHAR(16),
	LOGHOR VARCHAR(12),
	LOGTYP INT,
	LOGMSG VARCHAR(2000),
	LOGOBS VARCHAR(6000),
	LOGREF VARCHAR(8000),
	LOGSTS INT,
	LOGPRT VARCHAR(30),
	LOGEXR VARCHAR(60),
	LOGTPD VARCHAR(20),
	LOGSER VARCHAR(20),
	LOGNDC INT,
	LOGLIN INT,
	LOGDT1 VARCHAR(2000),
	LOGDT2 VARCHAR(2000),
	LOGDT3 VARCHAR(2000),
	LOGDT4 VARCHAR(2000),
	LOGDT5 VARCHAR(2000),
	LOGUSR VARCHAR(120),
	LOGACL VARCHAR(4000),
	LOGVND VARCHAR(50)  NULL ,
	LOGSYNCR VARCHAR(1) NULL ,
	LOGTIPO VARCHAR(1) null,
	LOGTERM BIGINT null
); 
CREATE UNIQUE INDEX LOG3 ON MSLOG (LOGSTP, LOGTERM);
CREATE INDEX LOG1 ON MSLOG (LOGSTP);
CREATE INDEX LOG2 ON MSLOG (LOGEXR,LOGTPD,LOGSER,LOGNDC,LOGLIN);


